import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { applyRepoEnv } from "@/lib/env/repoEnv";
import { retrieveHelp } from "@/lib/patAssistant/retrieveHelp";
import { PUBLIC_AUDIENCE } from "@/lib/patAssistant/audienceTokens";
import { GLOBAL_VERTICAL_ID } from "@/lib/verticals/context";
import { loadCorpusArticleFiles } from "@/lib/corpus/articleFiles";

/**
 * B1 retrieval goldens + walls.
 *
 * Two questions this suite answers, and they are different questions:
 *
 *   1. Does the public shelf actually RETRIEVE for a public caller? A corpus
 *      that imports cleanly and returns nothing is indistinguishable from no
 *      corpus at all, and the import counts alone cannot tell them apart.
 *   2. Can a public article reach anyone it should not, or a signed-in article
 *      reach the public shelf? Those are the walls, and they are asserted from
 *      both sides.
 *
 * DB-backed, and SKIPS visibly when Postgres is unreachable — matching the other
 * corpus suites. It asserts on paths rather than prose, so a wording pass in a
 * later authoring box does not break the walls.
 */

applyRepoEnv();

const DB_TIMEOUT_MS = 60_000;
let prisma: typeof import("@/lib/prisma").default;
let dbAvailable = false;
let indexedB1 = 0;

beforeAll(async () => {
  prisma = (await import("@/lib/prisma")).default;
  try {
    await prisma.$queryRaw`SELECT 1`;
    dbAvailable = true;
  } catch {
    dbAvailable = false;
    return;
  }
  indexedB1 = await prisma.knowledgeSource.count({
    where: { OR: [{ path: { startsWith: "help/public/" } }, { path: { startsWith: "help/glossary/" } }] },
  });
}, DB_TIMEOUT_MS);

afterAll(async () => {
  if (dbAvailable) await prisma.$disconnect();
});

const paths = (rows: Awaited<ReturnType<typeof retrieveHelp>>) => rows.map((row) => row.sourcePath);
const publicOpts = { publicEntry: true as const };

describe("the B1 shelf is indexed", () => {
  it("has all 30 articles on disk, tagged from frontmatter", () => {
    const files = loadCorpusArticleFiles().filter(
      (a) => a.path.startsWith("help/public/") || a.path.startsWith("help/glossary/")
    );
    expect(files).toHaveLength(30);
    expect(files.filter((a) => a.roleAccess.includes(PUBLIC_AUDIENCE))).toHaveLength(20);
    expect(files.filter((a) => a.roleAccess.length === 0)).toHaveLength(10);
    // Vertical-neutral: these describe PAT itself, not accounting.
    expect(files.every((a) => a.verticalId === GLOBAL_VERTICAL_ID)).toBe(true);
    expect(files.every((a) => a.depthTier === "CORE")).toBe(true);
  });

  it("indexed all 30 into KnowledgeSource", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    expect(indexedB1).toBe(30);
  }, DB_TIMEOUT_MS);
});

/**
 * GOLDEN QUERIES — public shelf.
 *
 * Each is a question a signed-out visitor would plausibly type, paired with the
 * article that should answer it. Asserted as "the expected article is among the
 * results", not "is rank 1": lexical ranking across 30 long articles on related
 * topics is legitimately close, and pinning exact rank would make this suite
 * fail on an unrelated authoring pass rather than on a real regression.
 */
const PUBLIC_GOLDENS: Array<{ query: string; expect: string }> = [
  { query: "what is PAT", expect: "help/public/what-is-pat.md" },
  { query: "how are PAT scores calculated", expect: "help/public/how-pat-scoring-works.md" },
  { query: "are PAT scores generated by AI", expect: "help/public/why-pat-scores-are-not-ai-generated.md" },
  { query: "what are the five pillars", expect: "help/public/the-five-pillars-briefly.md" },
  { query: "is there a free tier", expect: "help/public/why-pat-has-no-free-tier.md" },
  { query: "how does PAT protect benchmark integrity", expect: "help/public/how-pat-protects-benchmark-integrity.md" },
  { query: "what is an ecosystem in PAT", expect: "help/public/what-an-ecosystem-is-in-pat.md" },
  { query: "security and privacy posture", expect: "help/public/security-and-privacy-posture.md" },
];

describe("golden queries — the public shelf retrieves for the public entry path", () => {
  for (const golden of PUBLIC_GOLDENS) {
    it(`"${golden.query}" retrieves ${golden.expect.replace("help/public/", "")}`, async (ctx) => {
      if (!dbAvailable) return ctx.skip();
      const rows = await retrieveHelp(golden.query, PUBLIC_AUDIENCE, 5, publicOpts);
      expect(rows.length).toBeGreaterThan(0);
      expect(paths(rows)).toContain(golden.expect);
    }, DB_TIMEOUT_MS);
  }

  it("only ever returns public-shelf articles to a public caller", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    // Across every golden, nothing from the signed-in glossary may appear.
    for (const golden of PUBLIC_GOLDENS) {
      const rows = await retrieveHelp(golden.query, PUBLIC_AUDIENCE, 5, publicOpts);
      for (const rowPath of paths(rows)) {
        expect({ query: golden.query, rowPath, leaked: rowPath.startsWith("help/glossary/") }).toEqual({
          query: golden.query,
          rowPath,
          leaked: false,
        });
      }
    }
  }, DB_TIMEOUT_MS);
});

/**
 * The wall, from both sides. These are the assertions that matter most: a
 * golden that passes proves the corpus works, but only these prove it is safe.
 */
describe("walls — public articles NEVER reach a signed-in-only ask, and vice versa", () => {
  const SIGNED_IN_AUDIENCES = ["firm", "vendor", "individual"] as const;

  it("a signed-in caller never retrieves a public-shelf article", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    // help/public/* is roleAccess ["public"], and a signed-in audience is not
    // "public", so the roleAccess predicate excludes it in SQL.
    for (const audience of SIGNED_IN_AUDIENCES) {
      for (const golden of PUBLIC_GOLDENS.slice(0, 4)) {
        const rows = await retrieveHelp(golden.query, audience, 5, { membershipPlan: "PRO" });
        const leaked = paths(rows).filter((p) => p.startsWith("help/public/"));
        expect({ audience, query: golden.query, leaked }).toEqual({
          audience,
          query: golden.query,
          leaked: [],
        });
      }
    }
  }, DB_TIMEOUT_MS);

  it("a signed-in caller DOES retrieve the signed-in glossary", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    // The counterpart to the wall above: proving exclusion is only meaningful
    // alongside proving the intended access still works.
    const rows = await retrieveHelp("what is the alignment delta", "firm", 5, { membershipPlan: "PRO" });
    expect(paths(rows)).toContain("help/glossary/alignment-delta.md");
  }, DB_TIMEOUT_MS);

  it("the public entry path never reaches the signed-in glossary", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    const rows = await retrieveHelp("what is the alignment delta", PUBLIC_AUDIENCE, 5, publicOpts);
    expect(paths(rows).filter((p) => p.startsWith("help/glossary/"))).toEqual([]);
  }, DB_TIMEOUT_MS);

  it("a signed-in caller CLAIMING the public audience gets nothing (CORPUS-INFRA)", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    // Without publicEntry the request is refused before any query is issued —
    // an authenticated session must never be able to claim the public audience.
    const rows = await retrieveHelp("what is PAT", PUBLIC_AUDIENCE, 5, { membershipPlan: "ELITE" });
    expect(rows).toEqual([]);
  }, DB_TIMEOUT_MS);

  it("the public path stays CORE-only even if handed an ELITE plan", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    const rows = await retrieveHelp("what is PAT", PUBLIC_AUDIENCE, 5, {
      publicEntry: true,
      membershipPlan: "ELITE",
    });
    expect(rows.length).toBeGreaterThan(0);
    expect(paths(rows).every((p) => p.startsWith("help/public/"))).toBe(true);
  }, DB_TIMEOUT_MS);

  it("vertical-neutral content survives a vertical-scoped request", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    // B1 is stored verticalId="global". A request scoped to accounting must
    // still see it, or the shelf vanishes the moment vertical filtering is on.
    const rows = await retrieveHelp("what is PAT", PUBLIC_AUDIENCE, 5, {
      publicEntry: true,
      verticalId: "accounting",
    });
    expect(paths(rows)).toContain("help/public/what-is-pat.md");
  }, DB_TIMEOUT_MS);
});

/**
 * KNOWN LIMITATION, encoded rather than hidden.
 *
 * Retrieval is Postgres lexical FTS with the query terms OR-joined and ranked by
 * ts_rank. That was adequate for 36 short help articles. At B1 scale — 30
 * articles of ~3,000 words, all about the same product — common terms swamp the
 * discriminating one and the top-5 ranks cluster within ~1% of each other:
 *
 *   "scoring"                      -> how-pat-scoring-works.md at rank 1
 *   "how are PAT scores calculated"-> how-pat-scoring-works.md at rank 1
 *   "how does PAT scoring work"    -> NOT IN TOP 10 (ranks 0.0975..0.0964, tied)
 *
 * The natural phrasing loses to "what is PAT" because every article contains
 * "pat", "how" and "work". This is a ranking-quality problem introduced by
 * corpus scale, not by the import, and it is exactly the case retrieveHelp's
 * documented pgvector swap-seam exists for.
 *
 * It is asserted as the CURRENT behaviour so it cannot be forgotten: when
 * retrieval improves, this test fails, and the query graduates into
 * PUBLIC_GOLDENS above. A limitation with a failing test attached is a backlog
 * item; a limitation in a comment is folklore.
 */
describe("known limitation — lexical ranking at B1 scale", () => {
  it("still misses the natural phrasing of a scoring question", async (ctx) => {
    if (!dbAvailable) return ctx.skip();
    const rows = await retrieveHelp("how does PAT scoring work", PUBLIC_AUDIENCE, 10, publicOpts);
    const found = paths(rows).includes("help/public/how-pat-scoring-works.md");
    expect({
      note: "when this flips to true, promote the query into PUBLIC_GOLDENS and delete this test",
      found,
    }).toEqual({
      note: "when this flips to true, promote the query into PUBLIC_GOLDENS and delete this test",
      found: false,
    });
    // It does still retrieve SOMETHING relevant — the shelf is not silent.
    expect(rows.length).toBeGreaterThan(0);
  }, DB_TIMEOUT_MS);
});
