export type InsightContentDefinition = {
  key: string;
  title: string;
  tier: 1 | 2;
  locale: "en-US";
  audience: "firm" | "vendor";
  domain: "firm" | "vendor_alignment" | "vendor_product";
  summary: string;
  what: string;
  why: string;
  how: string;
  basisTemplate: string;
  confidenceDisclaimerTemplate: string;
  lockedState: {
    summary: string;
    what: string;
    why: string;
    how: string;
    basis: string;
    disclaimer: string;
  } | null;
};

export const ELITE_PLACEHOLDER_TITLE = "Coming soon";
export const ELITE_PLACEHOLDER_CTA = "Unlock with Elite membership";
export const ELITE_PLACEHOLDER_MESSAGE = `${ELITE_PLACEHOLDER_TITLE}. ${ELITE_PLACEHOLDER_CTA}.`;

const firmInsights = [
  {
    key: "firm_tier1_operating_baseline",
    title: "Operating baseline",
    tier: 1,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "Current-state firm alignment across the five PAT modules.",
    what: "A current-state synthesis of the five module results.",
    why: "It keeps the firm reading anchored to visible operating evidence instead of completion alone.",
    how: "Use it to understand where the firm is operating from today before making tooling or change decisions.",
    basisTemplate: "Use current module scores, capability evidence, and question clusters from the current firm PAT system.",
    confidenceDisclaimerTemplate: "Treat weak module coverage or thin capability evidence as early current-state signal only.",
    lockedState: null,
  },
  {
    key: "firm_tier1_automation_readiness",
    title: "Automation and AI readiness",
    tier: 1,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "How prepared the firm is for practical automation and responsible AI adoption.",
    what: "A PAT read on whether automation and AI can be expanded responsibly right now.",
    why: "Automation pacing depends on real operating readiness, not aspiration.",
    how: "Use it to pace adoption, training, and oversight rather than pushing automation into weak operating ground.",
    basisTemplate: "Use the latest automation, operating-model, and supporting capability evidence from the current firm PAT system.",
    confidenceDisclaimerTemplate: "Do not read thin current-state coverage as proof that automation will scale cleanly.",
    lockedState: null,
  },
  {
    key: "firm_tier1_data_and_controls",
    title: "Data and controls posture",
    tier: 1,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "What the firm’s current data flow, control discipline, and governance posture imply.",
    what: "A practical readout on data confidence, control maturity, and vendor-risk posture.",
    why: "Weak data and control posture distorts execution long before a benchmark layer would help.",
    how: "Use it to prioritize integration cleanup, governance work, and vendor evaluation discipline.",
    basisTemplate: "Use current data-flow, governance, and supporting capability evidence from the firm PAT assessment.",
    confidenceDisclaimerTemplate: "If data-flow and control evidence are partial, treat the interpretation as sample-thin only.",
    lockedState: null,
  },
  {
    key: "firm_tier1_change_alignment",
    title: "Change and market alignment",
    tier: 1,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "How prepared the firm is to change, prioritize, and align to market pressure.",
    what: "A readout on strategy execution, adaptability, and current market alignment.",
    why: "Change capacity matters only insofar as the current PAT evidence shows the firm can absorb it.",
    how: "Use it to frame what the firm should change first and where the organization is likely to absorb it well.",
    basisTemplate: "Use current strategy, operating-model, and change-related capability evidence from the firm PAT system.",
    confidenceDisclaimerTemplate: "No current-state PAT readout should be treated as forward projection or market forecast.",
    lockedState: null,
  },
  {
    key: "firm_tier2_projection",
    title: "Future-state projection",
    tier: 2,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "Projected operating posture based on stronger benchmark and capability layers.",
    what: "A future projection layer once PAT has enough benchmark and longitudinal depth.",
    why: "Projection is useful only when the evidence base is broad enough to trust.",
    how: "Unlock with Elite membership.",
    basisTemplate: "Reserved for future benchmark and projection logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that projection support exists yet.",
    lockedState: {
      summary: ELITE_PLACEHOLDER_TITLE + ".",
      what: "A restricted Elite insight reserved for future projection logic.",
      why: "Projection is not honest until broader evidence exists.",
      how: `${ELITE_PLACEHOLDER_CTA}.`,
      basis: "Projection evidence is not available in the current PAT product.",
      disclaimer: ELITE_PLACEHOLDER_CTA,
    },
  },
  {
    key: "firm_tier2_benchmark",
    title: "Peer benchmark view",
    tier: 2,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "Comparison against stronger benchmark cohorts and market-observed patterns.",
    what: "A future peer-relative view once PAT has defensible cohort support.",
    why: "Benchmarking without a real cohort frame would overstate what PAT knows.",
    how: "Unlock with Elite membership.",
    basisTemplate: "Reserved for future benchmark cohort logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that benchmark support exists yet.",
    lockedState: {
      summary: ELITE_PLACEHOLDER_TITLE + ".",
      what: "A restricted Elite insight reserved for future benchmark comparisons.",
      why: "Benchmark claims require a broader evidence base than the current PAT runtime has.",
      how: `${ELITE_PLACEHOLDER_CTA}.`,
      basis: "Benchmark evidence is not available in the current PAT product.",
      disclaimer: ELITE_PLACEHOLDER_CTA,
    },
  },
  {
    key: "firm_tier2_recommendation",
    title: "Recommendation engine",
    tier: 2,
    locale: "en-US",
    audience: "firm",
    domain: "firm",
    summary: "Richer PAT recommendation and sequencing once deeper data writes exist.",
    what: "A future recommendation layer for sequencing decisions once PAT has deeper evidence support.",
    why: "Recommendations are only useful when they are grounded in more than thin current-state signal.",
    how: "Unlock with Elite membership.",
    basisTemplate: "Reserved for future recommendation logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that recommendation support exists yet.",
    lockedState: {
      summary: ELITE_PLACEHOLDER_TITLE + ".",
      what: "A restricted Elite insight reserved for future sequencing guidance.",
      why: "Recommendation claims require deeper evidence than the current PAT runtime has.",
      how: `${ELITE_PLACEHOLDER_CTA}.`,
      basis: "Recommendation evidence is not available in the current PAT product.",
      disclaimer: ELITE_PLACEHOLDER_CTA,
    },
  },
] as const satisfies readonly InsightContentDefinition[];

const vendorAlignmentInsights = [
  {
    key: "operating-discipline-demand",
    title: "Operating discipline demand",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows how disciplined or unstable the current firm operating environment looks from the vendor side.",
    what: "A vendor-facing PAT readout of how much operating discipline firms are bringing into buying, onboarding, and implementation decisions.",
    why: "Vendors need to know whether the buyers in view are arriving from stable operating ground or from avoidable execution disorder.",
    how: "PAT reads this from current firm module scores, current module spread, and capability-backed question patterns tied to operating discipline, execution consistency, and visible measurement.",
    basisTemplate: "Use current firm module, capability, and question-cluster evidence only.",
    confidenceDisclaimerTemplate: "Do not read thin firm coverage as broad market evidence.",
    lockedState: null,
  },
  {
    key: "workflow-friction-pressure",
    title: "Workflow friction pressure",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Highlights where current firm-side alignment suggests workflow stress, handoff drag, or execution weakness.",
    what: "A PAT view of how much execution drag, handoff pressure, and day-to-day operating stress firms are signaling in their alignment assessments.",
    why: "Friction-heavy buyers need a different product story than firms already operating with discipline.",
    how: "This is grounded in current firm module scores, workflow-friction clusters, and the capability patterns most associated with handoff drag, day-to-day friction, and control strain.",
    basisTemplate: "Use current firm module, capability, and cluster evidence tied to workflow friction.",
    confidenceDisclaimerTemplate: "Early current-state vendor signal is not the same as broad market proof.",
    lockedState: null,
  },
  {
    key: "automation-receptivity",
    title: "Automation receptivity",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows whether current firms look prepared to absorb automation-oriented product value without destabilizing delivery.",
    what: "A vendor-facing PAT readout of whether the current firm signal suggests practical openness to automation and AI-enabled delivery improvement.",
    why: "Automation-oriented products succeed differently in firms that are prepared for change than in firms still struggling with operating basics.",
    how: "PAT grounds this in Automation and AI Readiness, Strategy and Change Alignment, and the question clusters tied to repeatable automation support, responsible AI use, and change adoption.",
    basisTemplate: "Use current automation, change, and supporting capability evidence only.",
    confidenceDisclaimerTemplate: "Thin current-state evidence should not be read as forecast demand.",
    lockedState: null,
  },
  {
    key: "integration-strain",
    title: "Integration strain",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows how much system-linkage and data-flow stress firms are signaling before a vendor enters implementation.",
    what: "A PAT readout of how much integration burden, system discontinuity, and data-flow stress the current firm base appears to carry.",
    why: "Products that depend on clean data movement and reliable stack connection face materially higher risk when firms are already strained here.",
    how: "PAT grounds this in Integration and Data Flow Maturity, related capability scores, and the current question clusters tied to data reliability, system connection, and measurable visibility.",
    basisTemplate: "Use current integration and data-flow evidence only.",
    confidenceDisclaimerTemplate: "Do not read current integration strain as benchmark or forecast intelligence.",
    lockedState: null,
  },
  {
    key: "governance-sensitivity",
    title: "Governance sensitivity",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows how heavily control posture, vendor oversight, and risk discipline are likely to shape vendor adoption conditions.",
    what: "A vendor-facing PAT readout of how sensitive the current buyer environment is to governance, control, and vendor-risk considerations.",
    why: "Highly governance-sensitive firms scrutinize trust, controls, rollout design, and vendor posture more heavily than firms buying from lighter operating conditions.",
    how: "PAT grounds this in Governance, Controls, and Vendor Risk, then cross-checks control resilience and data-flow evidence where operational trust is most likely to break.",
    basisTemplate: "Use current governance, control, and supporting evidence only.",
    confidenceDisclaimerTemplate: "Thin governance signal should be treated as sample-thin rather than market-wide.",
    lockedState: null,
  },
  {
    key: "change-absorbency",
    title: "Change absorbency",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows whether firms appear able to absorb change cleanly or whether change pressure is likely to create adoption drag.",
    what: "A PAT view of whether firms look able to absorb operating change, implementation sequencing, and rollout pressure without losing coherence.",
    why: "Even strong products stall when the buyer can agree on the strategy but cannot absorb the change burden operationally.",
    how: "PAT grounds this in Strategy, Change Readiness, and Market Alignment, then checks change-enablement and operating-clarity evidence from the supporting capability layer.",
    basisTemplate: "Use current change-readiness and supporting capability evidence only.",
    confidenceDisclaimerTemplate: "Do not present thin change-readiness signal as future-state projection.",
    lockedState: null,
  },
  {
    key: "uneven-maturity-variance",
    title: "Uneven maturity and module variance",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows whether firms look evenly developed across the PAT model or materially uneven from module to module.",
    what: "A vendor-facing PAT readout of how evenly or unevenly maturity is distributed across the current firm assessment base.",
    why: "Uneven buyers often create implementation surprises because one operating area looks strong while another becomes the hidden constraint.",
    how: "PAT grounds this in cross-module variance, the spread between strongest and weakest modules, and the distribution of current capability scores across the current firm system.",
    basisTemplate: "Use current cross-module spread and capability distribution only.",
    confidenceDisclaimerTemplate: "Variance under thin sample should be treated as sample-thin, not market-wide.",
    lockedState: null,
  },
  {
    key: "implementation-risk-posture",
    title: "Implementation risk posture",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Shows the overall implementation risk environment vendors are likely walking into based on current firm PAT evidence.",
    what: "A PAT synthesis of whether the current firm base looks implementation-friendly, cautionary, or materially risk-weighted.",
    why: "Implementation risk is where promising product fit still turns into delays, workarounds, and damaged trust if the buyer context is weak.",
    how: "PAT combines the current data-flow, governance, change, and friction patterns already visible in current firm PAT submissions to describe the risk posture honestly without projecting beyond the data.",
    basisTemplate: "Use current implementation-related PAT evidence only.",
    confidenceDisclaimerTemplate: "No current vendor alignment insight should be read as forecast or scenario support.",
    lockedState: null,
  },
  {
    key: "benchmark-comparison",
    title: "Benchmark comparison",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Peer-relative comparison across benchmark cohorts and market segments.",
    what: "A future PAT layer for benchmark-relative vendor interpretation rather than current-state signal only.",
    why: "Comparison matters, but only when the benchmark frame is defensible and broad enough to trust.",
    how: "This remains locked until Elite membership can combine current firm alignment signal with real benchmark cohorts safely.",
    basisTemplate: "Reserved for future benchmark cohort logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that benchmark support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future benchmark comparisons.",
      why: "Benchmark claims require broader and more durable evidence than the current PAT runtime has.",
      how: "Unlock with Elite membership.",
      basis: "Benchmark evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
  {
    key: "forward-projection",
    title: "Forward projection",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Forward-looking vendor demand and adoption projection.",
    what: "A future PAT layer for forward demand interpretation and likely next-state movement.",
    why: "Projection matters, but only when PAT has enough longitudinal and benchmark evidence to avoid bluffing.",
    how: "This remains locked until Elite membership can combine current signal with durable time-series and projection logic honestly.",
    basisTemplate: "Reserved for future projection logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that projection support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future forward-looking interpretation.",
      why: "Projection claims require longitudinal evidence the current PAT runtime does not have.",
      how: "Unlock with Elite membership.",
      basis: "Projection evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
  {
    key: "scenario-simulation",
    title: "Scenario simulation",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_alignment",
    summary: "Simulation of likely vendor outcomes under different operating and market conditions.",
    what: "A future PAT layer for scenario testing and market-sensitive vendor planning.",
    why: "Simulation is useful only when the model has enough breadth and stability to support counterfactual reasoning responsibly.",
    how: "This remains locked until Elite membership can support scenario simulation without inventing unsupported market intelligence.",
    basisTemplate: "Reserved for future scenario logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that simulation support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future scenario testing.",
      why: "Scenario claims require broader evidence and model stability than the current PAT runtime has.",
      how: "Unlock with Elite membership.",
      basis: "Scenario evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
] as const satisfies readonly InsightContentDefinition[];

const vendorProductInsights = [
  {
    key: "current-product-fit",
    title: "Current product-fit signal",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "Reflective Pro membership readout from the latest vendor product assessment.",
    what: "A current-state PAT readout of how convincingly the product supports the declared utility set in real operating conditions.",
    why: "Product-fit is not a branding claim. It matters because firms and operators feel workflow mismatch immediately in delivery, onboarding, and daily use.",
    how: "PAT builds this signal from the vendor assessment sections most directly tied to real usage: Workflow Fit, Operational Dependence, Adoption Ease, and Measurable Value across each declared utility.",
    basisTemplate: "Use vendor self-reported and firm-reviewed product evidence only.",
    confidenceDisclaimerTemplate: "Thin firm review coverage should be treated as sample-thin rather than broadly confirmed.",
    lockedState: null,
  },
  {
    key: "implementation-friction",
    title: "Implementation friction view",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "Where the current product posture suggests delivery friction or readiness strength.",
    what: "A PAT view into how heavy or manageable implementation, migration, configuration, and rollout effort is likely to feel for the product.",
    why: "A product can look strong in demos and still fail in deployment. This insight matters because implementation friction changes timeline, risk, staffing, and customer confidence.",
    how: "PAT grounds this insight in Implementation and Migration, Integration Readiness, Configuration Depth, and Training and Onboarding responses for every declared utility.",
    basisTemplate: "Use vendor self-reported and firm-reviewed implementation evidence only.",
    confidenceDisclaimerTemplate: "Thin firm review coverage should be treated as sample-thin rather than broadly confirmed.",
    lockedState: null,
  },
  {
    key: "visibility-and-value",
    title: "Visibility and value signal",
    tier: 1,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "Current-state signal on visibility, reporting, and measurable value clarity.",
    what: "A current-state PAT readout of whether the product turns work into usable visibility, actionable reporting, and credible outcome evidence.",
    why: "Products that cannot show clear signal struggle to justify adoption, expansion, and trust. Visibility and value clarity determine whether buyers can defend the decision operationally.",
    how: "PAT derives this from Reporting and Visibility, Support, Trust, and Reliability, and Measurable Value question responses tied to each declared utility.",
    basisTemplate: "Use vendor self-reported and firm-reviewed value evidence only.",
    confidenceDisclaimerTemplate: "Current-state PAT value signal is not a benchmark or forecast claim.",
    lockedState: null,
  },
  {
    key: "market-comparison",
    title: "Market comparison view",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "How this product compares against broader market patterns and peers.",
    what: "A future comparison layer for peer-relative PAT positioning.",
    why: "Vendors eventually need external comparison, but only when the benchmark set is defensible.",
    how: "This remains locked until Elite membership adds broader market data and comparison logic.",
    basisTemplate: "Reserved for future benchmark product logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that product benchmark support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future product benchmark comparisons.",
      why: "Benchmark claims require broader market evidence than the current PAT runtime has.",
      how: "Unlock with Elite membership.",
      basis: "Product benchmark evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
  {
    key: "future-demand-projection",
    title: "Future demand projection",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "Projected utility demand and next-adjacent opportunity signal.",
    what: "A forward-looking PAT layer for utility demand and likely adjacent expansion opportunities.",
    why: "Forward demand matters for planning, packaging, and roadmap choices, but only if the underlying projection is honest.",
    how: "This remains locked until Elite membership adds enough signal depth to support projection without bluffing.",
    basisTemplate: "Reserved for future product projection logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that product projection support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future demand projection.",
      why: "Projection claims require more durable evidence than the current PAT runtime has.",
      how: "Unlock with Elite membership.",
      basis: "Product projection evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
  {
    key: "expansion-simulation",
    title: "Expansion simulation",
    tier: 2,
    locale: "en-US",
    audience: "vendor",
    domain: "vendor_product",
    summary: "Scenario modeling for future fit, packaging, and product expansion.",
    what: "A scenario layer for testing likely product expansion paths inside the PAT model.",
    why: "Expansion planning can be expensive and distracting if it is not anchored in real utility and adoption signal.",
    how: "This remains locked until Elite membership opens richer scenario modeling and wider evidence coverage.",
    basisTemplate: "Reserved for future product scenario logic.",
    confidenceDisclaimerTemplate: "PAT does not claim that product simulation support exists yet.",
    lockedState: {
      summary: "Coming soon.",
      what: "A restricted Elite insight reserved for future expansion simulation.",
      why: "Scenario claims require broader evidence than the current PAT runtime has.",
      how: "Unlock with Elite membership.",
      basis: "Product simulation evidence is not available in the current PAT product.",
      disclaimer: "Unlock with Elite membership",
    },
  },
] as const satisfies readonly InsightContentDefinition[];

export const insightContent = {
  firm: firmInsights,
  vendorAlignment: vendorAlignmentInsights,
  vendorProduct: vendorProductInsights,
} as const;

export function getFirmInsightContent(key: string) {
  return firmInsights.find((item) => item.key === key) ?? null;
}

export function getVendorAlignmentInsightContent(key: string) {
  return vendorAlignmentInsights.find((item) => item.key === key) ?? null;
}

export function getVendorProductInsightContent(key: string) {
  return vendorProductInsights.find((item) => item.key === key) ?? null;
}
