import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

/**
 * "data" lexicon (A2-iii): list every whole-word "data" in Leslie's help articles
 * as file:line so she can decide each one. This script EDITS NOTHING under help/;
 * it writes help/lexicon-data-occurrences.md only.
 *
 *   pnpm exec node --import tsx scripts/qa/lexicon-data-occurrences.ts
 */
const ROOT = process.cwd();
const HELP = path.join(ROOT, "help");
const OUT = path.join(HELP, "lexicon-data-occurrences.md");
const TECHNICAL = /\bdata flow\b|\bdatabase\b/i; // the allowed technical senses on a line

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((entry) => {
    const full = path.join(dir, entry);
    if (statSync(full).isDirectory()) return walk(full);
    return full.endsWith(".md") && !full.endsWith("lexicon-data-occurrences.md") ? [full] : [];
  });
}

type Hit = { file: string; line: number; technical: boolean; text: string };
const hits: Hit[] = [];
for (const file of walk(HELP).sort()) {
  const lines = readFileSync(file, "utf8").split("\n");
  lines.forEach((text, index) => {
    const count = (text.match(/\bdata\b/gi) ?? []).length;
    if (count === 0) return;
    hits.push({ file: path.relative(ROOT, file), line: index + 1, technical: TECHNICAL.test(text), text: text.trim() });
  });
}

const byDir = (prefix: string) => hits.filter((hit) => hit.file.startsWith(prefix));
const plain = hits.filter((hit) => !hit.technical);
const lines = [
  "# \"data\" occurrences in the help articles",
  "",
  "Generated by `scripts/qa/lexicon-data-occurrences.ts`. Nothing under `help/` was edited; every line below is for Leslie to decide.",
  "The Pat answer template now avoids the word (say answers / scores / results / responses) unless it is the technical term.",
  "",
  `- Lines containing the whole word \`data\` (any case): **${hits.length}** — help/public ${byDir("help/public").length}, help/glossary ${byDir("help/glossary").length}`,
  `- Of those, lines where it is the technical term (\`data flow\` module name, \`database\`): ${hits.length - plain.length}`,
  `- Lines to decide (plain-language sense): **${plain.length}**`,
  "",
  "| File:line | Technical? | Line |",
  "| --- | --- | --- |",
  ...hits.map((hit) => `| \`${hit.file}:${hit.line}\` | ${hit.technical ? "yes" : ""} | ${hit.text.replace(/\|/g, "\\|").slice(0, 160)} |`),
  "",
];
writeFileSync(OUT, lines.join("\n"));
console.log(`wrote ${path.relative(ROOT, OUT)}: ${hits.length} lines (${plain.length} plain-language, ${hits.length - plain.length} technical)`);
