-- AlterTable
ALTER TABLE "FirmMaturityIndex" ADD COLUMN     "bandMax" DOUBLE PRECISION NOT NULL DEFAULT 25,
ADD COLUMN     "bandMin" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "tier" TEXT NOT NULL DEFAULT 'FOUNDATIONAL';
